"""旧 ``ARRANGEMENTS``（BandProfile 39ジャンル）の編成の期待値（DESIGN.md §6.14「編成の対応表」。

旧実装を消す前に、旧クラスから生成して固定した。``{ジャンル: {チャンネル数: (((楽器名…), {楽器: 優先度}) の列, パン or None)}}``。
"""
LAYOUTS = {'acoustic-ssw': {4: (((('low', 'shaker', 'slap'), {'low': 2, 'shaker': 1, 'slap': 3}),
                       (('bass',), {'bass': 1}),
                       (('gtr',), {'gtr': 1}),
                       (('vox',), {'vox': 1})),
                      None),
                  6: (((('low', 'slap'), {'low': 2, 'slap': 3}),
                       (('shaker',), {'shaker': 1}),
                       (('bass',), {'bass': 1}),
                       (('gtr',), {'gtr': 1}),
                       (('vox',), {'vox': 1}),
                       (('vox',), {'vox': 1})),
                      (128, 164, 128, 84, 172, 100))},
 'anime-ost': {4: (((('crash', 'kick', 'ride', 'snare'), {'crash': 2, 'kick': 3, 'ride': 1, 'snare': 4}),
                    (('bass',), {'bass': 1}),
                    (('piano',), {'piano': 1}),
                    (('brass', 'sax', 'vln'), {'brass': 1, 'sax': 1, 'vln': 1})),
                   None),
               6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'ride'), {'crash': 2, 'ride': 1}),
                    (('bass',), {'bass': 1}),
                    (('piano',), {'piano': 1}),
                    (('brass', 'sax', 'vln'), {'brass': 1, 'sax': 1, 'vln': 1}),
                    (('brass', 'spic'), {'brass': 2, 'spic': 1})),
                   (128, 170, 128, 88, 150, 64)),
               8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'ride'), {'crash': 2, 'ride': 1}),
                    (('bass',), {'bass': 1}),
                    (('piano',), {'piano': 1}),
                    (('brass', 'sax', 'vln'), {'brass': 1, 'sax': 1, 'vln': 1}),
                    (('brass', 'spic'), {'brass': 2, 'spic': 1}),
                    (('brass', 'sax', 'vln'), {'brass': 1, 'sax': 1, 'vln': 1}),
                    (('vln',), {'vln': 1})),
                   (128, 170, 128, 88, 150, 64, 96, 160))},
 'bossa-nova': {4: (((('rim', 'shaker', 'surdo'), {'rim': 3, 'shaker': 1, 'surdo': 2}),
                     (('bass',), {'bass': 1}),
                     (('gtr',), {'gtr': 1}),
                     (('flute',), {'flute': 1})),
                    None),
                6: (((('rim', 'surdo'), {'rim': 3, 'surdo': 2}),
                     (('shaker',), {'shaker': 1}),
                     (('bass',), {'bass': 1}),
                     (('gtr',), {'gtr': 1}),
                     (('flute',), {'flute': 1}),
                     (('ep',), {'ep': 1})),
                    (128, 164, 128, 84, 172, 100))},
 'cinematic': {6: (((('piano',), {'piano': 1}),
                    (('vln',), {'vln': 1}),
                    (('vc',), {'vc': 1}),
                    (('horn',), {'horn': 1}),
                    (('choir',), {'choir': 1}),
                    (('swell', 'timp'), {'swell': 1, 'timp': 2})),
                   (100, 84, 176, 110, 128, 128)),
               8: (((('piano',), {'piano': 1}),
                    (('vln',), {'vln': 1}),
                    (('vla',), {'vla': 1}),
                    (('vc',), {'vc': 1}),
                    (('cb',), {'cb': 1}),
                    (('horn',), {'horn': 1}),
                    (('choir',), {'choir': 1}),
                    (('swell', 'timp'), {'swell': 1, 'timp': 2})),
                   (100, 84, 160, 176, 150, 110, 128, 128))},
 'city-pop': {4: (((('crash', 'hat', 'kick', 'snare', 'tamb'),
                    {'crash': 2, 'hat': 1, 'kick': 3, 'snare': 4, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1})),
                  None),
              6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1}),
                   (('cut',), {'cut': 1})),
                  (128, 164, 128, 84, 172, 48)),
              8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1}),
                   (('cut',), {'cut': 1}),
                   (('lead',), {'lead': 1}),
                   (('line',), {'line': 1})),
                  (128, 164, 128, 84, 172, 48, 96, 160))},
 'cool': {4: (((('hat', 'kick', 'rim', 'snare'), {'hat': 1, 'kick': 3, 'rim': 2, 'snare': 4}),
               (('bass',), {'bass': 1}),
               (('pad',), {'pad': 1}),
               (('lead',), {'lead': 1})),
              None),
          6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
               (('hat', 'rim'), {'hat': 1, 'rim': 2}),
               (('bass',), {'bass': 1}),
               (('pad',), {'pad': 1}),
               (('lead',), {'lead': 1}),
               (('lead',), {'lead': 1})),
              (128, 164, 128, 84, 150, 100)),
          8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
               (('hat', 'rim'), {'hat': 1, 'rim': 2}),
               (('bass',), {'bass': 1}),
               (('pad',), {'pad': 1}),
               (('lead',), {'lead': 1}),
               (('lead',), {'lead': 1}),
               (('voice',), {'voice': 1}),
               (('bell',), {'bell': 1})),
              (128, 164, 128, 84, 150, 100, 96, 160))},
 'dark-tense': {4: (((('taiko', 'tick'), {'taiko': 4, 'tick': 1}),
                     (('bass',), {'bass': 1}),
                     (('str',), {'str': 1}),
                     (('braam',), {'braam': 1})),
                    None),
                6: (((('taiko',), {'taiko': 1}),
                     (('tick',), {'tick': 1}),
                     (('bass',), {'bass': 1}),
                     (('str',), {'str': 1}),
                     (('braam',), {'braam': 1}),
                     (('impact', 'riser'), {'impact': 2, 'riser': 1})),
                    (128, 176, 128, 72, 110, 150)),
                8: (((('taiko',), {'taiko': 1}),
                     (('tick',), {'tick': 1}),
                     (('bass',), {'bass': 1}),
                     (('str',), {'str': 1}),
                     (('braam',), {'braam': 1}),
                     (('impact', 'riser'), {'impact': 2, 'riser': 1}),
                     (('choir',), {'choir': 1}),
                     (('braam',), {'braam': 1})),
                    (128, 176, 128, 72, 110, 150, 96, 160))},
 'dreamy': {4: (((('kick', 'rim'), {'kick': 1, 'rim': 2}),
                 (('bass',), {'bass': 1}),
                 (('pad',), {'pad': 1}),
                 (('arp',), {'arp': 1})),
                None),
            6: (((('kick', 'rim'), {'kick': 1, 'rim': 2}),
                 (('bass',), {'bass': 1}),
                 (('pad',), {'pad': 1}),
                 (('arp',), {'arp': 1}),
                 (('arp',), {'arp': 1}),
                 (('lead',), {'lead': 1})),
                (128, 128, 72, 176, 80, 150)),
            8: (((('kick', 'rim'), {'kick': 1, 'rim': 2}),
                 (('bass',), {'bass': 1}),
                 (('pad',), {'pad': 1}),
                 (('arp',), {'arp': 1}),
                 (('arp',), {'arp': 1}),
                 (('lead',), {'lead': 1}),
                 (('lead',), {'lead': 1}),
                 (('voice',), {'voice': 1})),
                (128, 128, 72, 176, 80, 150, 96, 160))},
 'edm': {4: (((('clap', 'hat', 'kick', 'snare'), {'clap': 3, 'hat': 1, 'kick': 4, 'snare': 4}),
              (('bass',), {'bass': 1}),
              (('pad',), {'pad': 1}),
              (('lead',), {'lead': 1})),
             None),
         6: (((('kick',), {'kick': 1}),
              (('clap', 'hat', 'snare'), {'clap': 2, 'hat': 1, 'snare': 3}),
              (('bass',), {'bass': 1}),
              (('pad',), {'pad': 1}),
              (('lead',), {'lead': 1}),
              (('impact', 'riser'), {'impact': 2, 'riser': 1})),
             (128, 150, 128, 88, 168, 128)),
         8: (((('kick',), {'kick': 1}),
              (('clap', 'hat', 'snare'), {'clap': 2, 'hat': 1, 'snare': 3}),
              (('bass',), {'bass': 1}),
              (('pad',), {'pad': 1}),
              (('lead',), {'lead': 1}),
              (('impact', 'riser'), {'impact': 2, 'riser': 1}),
              (('lead',), {'lead': 1}),
              (('pluck',), {'pluck': 1})),
             (128, 150, 128, 88, 168, 128, 96, 160))},
 'energetic': {4: (((('crash', 'hat', 'kick', 'snare', 'tom'),
                     {'crash': 2, 'hat': 1, 'kick': 3, 'snare': 4, 'tom': 3}),
                    (('bass',), {'bass': 1}),
                    (('gtr',), {'gtr': 1}),
                    (('lead',), {'lead': 1})),
                   None),
               6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'hat'), {'crash': 3, 'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('gtr',), {'gtr': 1}),
                    (('lead',), {'lead': 1}),
                    (('tom',), {'tom': 1})),
                   (128, 150, 128, 76, 180, 110)),
               8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'hat'), {'crash': 3, 'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('gtr',), {'gtr': 1}),
                    (('lead',), {'lead': 1}),
                    (('tom',), {'tom': 1}),
                    (('lead',), {'lead': 1}),
                    (('sbrass',), {'sbrass': 1})),
                   (128, 150, 128, 76, 180, 110, 96, 160))},
 'folk': {4: (((('clap', 'stomp', 'tamb'), {'clap': 3, 'stomp': 2, 'tamb': 1}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('fiddle',), {'fiddle': 1})),
              None),
          6: (((('clap', 'stomp'), {'clap': 3, 'stomp': 2}),
               (('tamb',), {'tamb': 1}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('fiddle',), {'fiddle': 1}),
               (('whistle',), {'whistle': 1})),
              (128, 164, 128, 84, 172, 100))},
 'hiphop': {4: (((('hat', 'kick', 'snare'), {'hat': 1, 'kick': 2, 'snare': 3}),
                 (('bass',), {'bass': 1}),
                 (('loop',), {'loop': 1}),
                 (('horn',), {'horn': 1})),
                None),
            6: (((('kick', 'snare'), {'kick': 2, 'snare': 3}),
                 (('hat',), {'hat': 1}),
                 (('bass',), {'bass': 1}),
                 (('loop',), {'loop': 1}),
                 (('horn',), {'horn': 1}),
                 (('str',), {'str': 1})),
                (128, 164, 128, 84, 172, 100))},
 'house': {4: (((('clap', 'kick', 'ohat', 'rim', 'shaker'), {'clap': 3, 'kick': 4, 'ohat': 1, 'rim': 2, 'shaker': 1}),
                (('bass',), {'bass': 1}),
                (('stab',), {'stab': 1}),
                (('pad',), {'pad': 1})),
               None),
           6: (((('kick',), {'kick': 1}),
                (('clap', 'ohat', 'rim'), {'clap': 3, 'ohat': 1, 'rim': 2}),
                (('bass',), {'bass': 1}),
                (('stab',), {'stab': 1}),
                (('pad',), {'pad': 1}),
                (('shaker',), {'shaker': 1})),
               (128, 150, 128, 96, 64, 184)),
           8: (((('kick',), {'kick': 1}),
                (('clap', 'ohat', 'rim'), {'clap': 3, 'ohat': 1, 'rim': 2}),
                (('bass',), {'bass': 1}),
                (('stab',), {'stab': 1}),
                (('pad',), {'pad': 1}),
                (('shaker',), {'shaker': 1}),
                (('stab',), {'stab': 1}),
                (('chop',), {'chop': 1})),
               (128, 150, 128, 96, 64, 184, 96, 160))},
 'indie-rock': {4: (((('crash', 'hat', 'kick', 'snare', 'tamb'),
                      {'crash': 2, 'hat': 1, 'kick': 3, 'snare': 4, 'tamb': 1}),
                     (('bass',), {'bass': 1}),
                     (('arp',), {'arp': 1}),
                     (('lead',), {'lead': 1})),
                    None),
                6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                     (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 1}),
                     (('bass',), {'bass': 1}),
                     (('arp',), {'arp': 1}),
                     (('lead',), {'lead': 1}),
                     (('gtr2',), {'gtr2': 1})),
                    (128, 160, 128, 80, 176, 56)),
                8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                     (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 1}),
                     (('bass',), {'bass': 1}),
                     (('arp',), {'arp': 1}),
                     (('lead',), {'lead': 1}),
                     (('gtr2',), {'gtr2': 1}),
                     (('lead',), {'lead': 1}),
                     (('organ',), {'organ': 1})),
                    (128, 160, 128, 80, 176, 56, 96, 160))},
 'jpop-80s': {4: (((('crash', 'hat', 'kick', 'snare', 'tamb'),
                    {'crash': 2, 'hat': 1, 'kick': 3, 'snare': 4, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1})),
                  None),
              6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1}),
                   (('brass',), {'brass': 1})),
                  (128, 164, 128, 84, 172, 56)),
              8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('crash', 'hat', 'tamb'), {'crash': 3, 'hat': 1, 'tamb': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep',), {'ep': 1}),
                   (('lead',), {'lead': 1}),
                   (('brass',), {'brass': 1}),
                   (('lead',), {'lead': 1}),
                   (('line',), {'line': 1})),
                  (128, 164, 128, 84, 172, 56, 96, 160))},
 'jrock-90s': {4: (((('crash', 'hat', 'kick', 'snare'), {'crash': 2, 'hat': 1, 'kick': 3, 'snare': 4}),
                    (('bass',), {'bass': 1}),
                    (('arp', 'gtr'), {'arp': 1, 'gtr': 1}),
                    (('lead',), {'lead': 1})),
                   None),
               6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'hat'), {'crash': 3, 'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('gtr',), {'gtr': 1}),
                    (('lead',), {'lead': 1}),
                    (('arp',), {'arp': 1})),
                   (128, 150, 128, 72, 184, 96)),
               8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('crash', 'hat'), {'crash': 3, 'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('gtr',), {'gtr': 1}),
                    (('lead',), {'lead': 1}),
                    (('arp',), {'arp': 1}),
                    (('lead',), {'lead': 1}),
                    (('line',), {'line': 1})),
                   (128, 150, 128, 72, 184, 96, 96, 160))},
 'jrpg': {4: (((('snare', 'timp'), {'snare': 1, 'timp': 2}),
               (('harp',), {'harp': 1}),
               (('cello',), {'cello': 1}),
               (('flute', 'tpt'), {'flute': 1, 'tpt': 1})),
              None),
          6: (((('snare', 'timp'), {'snare': 1, 'timp': 2}),
               (('harp',), {'harp': 1}),
               (('cello',), {'cello': 1}),
               (('str',), {'str': 1}),
               (('flute', 'tpt'), {'flute': 1, 'tpt': 1}),
               (('brass',), {'brass': 1})),
              (128, 84, 128, 172, 150, 100)),
          8: (((('snare', 'timp'), {'snare': 1, 'timp': 2}),
               (('harp',), {'harp': 1}),
               (('cello',), {'cello': 1}),
               (('str',), {'str': 1}),
               (('flute', 'tpt'), {'flute': 1, 'tpt': 1}),
               (('brass',), {'brass': 1}),
               (('flute', 'tpt'), {'flute': 1, 'tpt': 1}),
               (('choir',), {'choir': 1})),
              (128, 84, 128, 172, 150, 100, 96, 160))},
 'lofi-chill': {4: (((('kick', 'rim', 'shaker'), {'kick': 3, 'rim': 4, 'shaker': 1}),
                     (('bass',), {'bass': 1}),
                     (('gtr',), {'gtr': 1}),
                     (('lead',), {'lead': 1})),
                    None),
                6: (((('kick', 'rim'), {'kick': 1, 'rim': 2}),
                     (('shaker',), {'shaker': 1}),
                     (('bass',), {'bass': 1}),
                     (('gtr',), {'gtr': 1}),
                     (('lead',), {'lead': 1}),
                     (('rain',), {'rain': 1})),
                    (128, 164, 128, 84, 172, 128)),
                8: (((('kick', 'rim'), {'kick': 1, 'rim': 2}),
                     (('shaker',), {'shaker': 1}),
                     (('bass',), {'bass': 1}),
                     (('gtr',), {'gtr': 1}),
                     (('lead',), {'lead': 1}),
                     (('rain',), {'rain': 1}),
                     (('lead',), {'lead': 1}),
                     (('ep',), {'ep': 1})),
                    (128, 164, 128, 84, 172, 128, 96, 160))},
 'lofi-hiphop': {4: (((('hat', 'kick', 'snare'), {'hat': 1, 'kick': 3, 'snare': 4}),
                      (('bass',), {'bass': 1}),
                      (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                      (('lead',), {'lead': 1})),
                     None),
                 6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                      (('hat',), {'hat': 1}),
                      (('bass',), {'bass': 1}),
                      (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                      (('lead',), {'lead': 1}),
                      (('vinyl',), {'vinyl': 1})),
                     (128, 164, 128, 90, 170, 128)),
                 8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                      (('hat',), {'hat': 1}),
                      (('bass',), {'bass': 1}),
                      (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                      (('lead',), {'lead': 1}),
                      (('vinyl',), {'vinyl': 1}),
                      (('lead',), {'lead': 1}),
                      (('padline',), {'padline': 1})),
                     (128, 164, 128, 90, 170, 128, 96, 160))},
 'neo-soul': {4: (((('hat', 'kick', 'rim', 'snare'), {'hat': 1, 'kick': 3, 'rim': 2, 'snare': 4}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1})),
                  None),
              6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('hat', 'rim'), {'hat': 1, 'rim': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1})),
                  (128, 164, 128, 84, 150, 180)),
              8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('hat', 'rim'), {'hat': 1, 'rim': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('gtr',), {'gtr': 1})),
                  (128, 164, 128, 84, 150, 180, 96, 160))},
 'pop': {4: (((('crash', 'hat', 'kick', 'shaker', 'snare'),
               {'crash': 2, 'hat': 2, 'kick': 3, 'shaker': 1, 'snare': 4}),
              (('bass',), {'bass': 1}),
              (('piano',), {'piano': 1}),
              (('lead',), {'lead': 1})),
             None),
         6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
              (('crash', 'hat', 'shaker'), {'crash': 3, 'hat': 2, 'shaker': 1}),
              (('bass',), {'bass': 1}),
              (('piano',), {'piano': 1}),
              (('lead',), {'lead': 1}),
              (('pad',), {'pad': 1})),
             (128, 160, 128, 88, 168, 64)),
         8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
              (('crash', 'hat', 'shaker'), {'crash': 3, 'hat': 2, 'shaker': 1}),
              (('bass',), {'bass': 1}),
              (('piano',), {'piano': 1}),
              (('lead',), {'lead': 1}),
              (('pad',), {'pad': 1}),
              (('lead',), {'lead': 1}),
              (('line',), {'line': 1})),
             (128, 160, 128, 88, 168, 64, 96, 160))},
 'racing-breaks': {4: (((('crash', 'hat', 'kick', 'ohat', 'ride', 'snare'),
                         {'crash': 2, 'hat': 1, 'kick': 3, 'ohat': 2, 'ride': 2, 'snare': 4}),
                        (('bass',), {'bass': 1}),
                        (('ep',), {'ep': 1}),
                        (('vox',), {'vox': 1})),
                       None),
                   6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                        (('crash', 'hat', 'ohat', 'ride'), {'crash': 3, 'hat': 1, 'ohat': 2, 'ride': 2}),
                        (('bass',), {'bass': 1}),
                        (('ep',), {'ep': 1}),
                        (('pad',), {'pad': 1}),
                        (('vox',), {'vox': 1})),
                       (128, 164, 128, 88, 64, 160)),
                   8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                        (('crash', 'hat', 'ohat', 'ride'), {'crash': 3, 'hat': 1, 'ohat': 2, 'ride': 2}),
                        (('bass',), {'bass': 1}),
                        (('ep',), {'ep': 1}),
                        (('pad',), {'pad': 1}),
                        (('vox',), {'vox': 1}),
                        (('vox',), {'vox': 1}),
                        (('brass',), {'brass': 1})),
                       (128, 164, 128, 88, 64, 160, 96, 184))},
 'rnb-soul': {4: (((('hat', 'kick', 'rim', 'snare'), {'hat': 1, 'kick': 3, 'rim': 2, 'snare': 4}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1})),
                  None),
              6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('hat', 'rim'), {'hat': 1, 'rim': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('str', 'str_dom13'), {'str': 1, 'str_dom13': 1})),
                  (128, 160, 128, 88, 140, 60)),
              8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                   (('hat', 'rim'), {'hat': 1, 'rim': 2}),
                   (('bass',), {'bass': 1}),
                   (('ep', 'ep_dom13'), {'ep': 1, 'ep_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('str', 'str_dom13'), {'str': 1, 'str_dom13': 1}),
                   (('lead',), {'lead': 1}),
                   (('flute',), {'flute': 1})),
                  (128, 160, 128, 88, 140, 60, 96, 160))},
 'rock': {4: (((('crash', 'hat', 'kick', 'ride', 'snare', 'tom'),
                {'crash': 2, 'hat': 1, 'kick': 3, 'ride': 1, 'snare': 4, 'tom': 3}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('lead',), {'lead': 1})),
              None),
          6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
               (('crash', 'hat', 'ride'), {'crash': 3, 'hat': 1, 'ride': 1}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('lead',), {'lead': 1}),
               (('tom',), {'tom': 1})),
              (128, 150, 128, 72, 184, 110)),
          8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
               (('crash', 'hat', 'ride'), {'crash': 3, 'hat': 1, 'ride': 1}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('lead',), {'lead': 1}),
               (('tom',), {'tom': 1}),
               (('lead',), {'lead': 1}),
               (('organ',), {'organ': 1})),
              (128, 150, 128, 72, 184, 110, 96, 160))},
 'synthwave': {4: (((('hat', 'kick', 'snare'), {'hat': 1, 'kick': 3, 'snare': 4}),
                    (('bass',), {'bass': 1}),
                    (('pad',), {'pad': 1}),
                    (('lead',), {'lead': 1})),
                   None),
               6: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('hat',), {'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('pad',), {'pad': 1}),
                    (('lead',), {'lead': 1}),
                    (('arp',), {'arp': 1})),
                   (128, 164, 128, 80, 150, 190)),
               8: (((('kick', 'snare'), {'kick': 1, 'snare': 2}),
                    (('hat',), {'hat': 1}),
                    (('bass',), {'bass': 1}),
                    (('pad',), {'pad': 1}),
                    (('lead',), {'lead': 1}),
                    (('arp',), {'arp': 1}),
                    (('lead',), {'lead': 1}),
                    (('arp',), {'arp': 1})),
                   (128, 164, 128, 80, 150, 190, 96, 160))},
 'trailer': {6: (((('snare', 'taiko', 'tom'), {'snare': 2, 'taiko': 3, 'tom': 2}),
                  (('braam',), {'braam': 1}),
                  (('spic',), {'spic': 1}),
                  (('cello',), {'cello': 1}),
                  (('choir',), {'choir': 1}),
                  (('vln',), {'vln': 1})),
                 (128, 110, 80, 128, 170, 90)),
             8: (((('taiko',), {'taiko': 1}),
                  (('snare', 'tom'), {'snare': 2, 'tom': 1}),
                  (('braam',), {'braam': 1}),
                  (('spic',), {'spic': 1}),
                  (('cello',), {'cello': 1}),
                  (('choir',), {'choir': 1}),
                  (('vln',), {'vln': 1}),
                  (('impact', 'riser'), {'impact': 2, 'riser': 1})),
                 (128, 150, 110, 80, 128, 170, 90, 128))},
 'uplifting': {4: (((('clap', 'kick', 'ohat', 'snare'), {'clap': 3, 'kick': 4, 'ohat': 1, 'snare': 4}),
                    (('bass',), {'bass': 1}),
                    (('saw',), {'saw': 1}),
                    (('arp',), {'arp': 1})),
                   None),
               6: (((('kick',), {'kick': 1}),
                    (('clap', 'ohat', 'snare'), {'clap': 2, 'ohat': 1, 'snare': 3}),
                    (('bass',), {'bass': 1}),
                    (('saw',), {'saw': 1}),
                    (('arp',), {'arp': 1}),
                    (('lead',), {'lead': 1})),
                   (128, 150, 128, 96, 176, 64)),
               8: (((('kick',), {'kick': 1}),
                    (('clap', 'ohat', 'snare'), {'clap': 2, 'ohat': 1, 'snare': 3}),
                    (('bass',), {'bass': 1}),
                    (('saw',), {'saw': 1}),
                    (('arp',), {'arp': 1}),
                    (('lead',), {'lead': 1}),
                    (('lead',), {'lead': 1}),
                    (('choir',), {'choir': 1})),
                   (128, 150, 128, 96, 176, 64, 96, 160))},
 'warm': {4: (((('low', 'shaker', 'slap'), {'low': 2, 'shaker': 1, 'slap': 3}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('piano',), {'piano': 1})),
              None),
          6: (((('low', 'slap'), {'low': 2, 'slap': 3}),
               (('shaker',), {'shaker': 1}),
               (('bass',), {'bass': 1}),
               (('gtr',), {'gtr': 1}),
               (('piano',), {'piano': 1}),
               (('flute',), {'flute': 1})),
              (128, 164, 128, 84, 172, 100))}}
