"""GUI の文言（日本語・英語）。CLI の ``cli.MESSAGES`` と同じ考え方で、キー → 文言の表。

ジャンル名・説明・区分名は CLI（``--list-genres --json``）から受け取るので、ここには書かない。
"""
from __future__ import annotations

import locale

TEXTS = {
    "ja": {
        "title": "ModWeaver",
        "menu_file": "ファイル",
        "menu_open_folder": "保存フォルダを開く",
        "menu_quit": "終了",
        "menu_view": "表示",
        "menu_language": "言語 (Language)",
        "menu_help": "ヘルプ",
        "menu_cli_help": "CLI の使い方...",
        "menu_about": "ModWeaver について",
        "loading": "ジャンル一覧を読み込み中...",
        "load_failed": "CLI からジャンル一覧を読み込めませんでした。",
        "genres": "ジャンル",
        "search": "検索:",
        "all_categories": "すべて",
        "random_genre": "ジャンルもランダムに選ぶ",
        "random_genre_desc": "生成のたびに、下の設定（テンポ・チャンネル数）で作れるジャンルからランダムに選びます。",
        "category": "区分",
        "aliases": "別名",
        "tempo_limit": "テンポ {lo}〜{hi}",
        "channel_choices": "チャンネル数 {choices}",
        "settings": "設定",
        "tempo": "テンポ (BPM)",
        "auto_genre": "ジャンルに任せる",
        "fixed": "固定",
        "range": "範囲",
        "channels": "チャンネル数",
        "seed": "シード",
        "seed_random": "毎回ランダム",
        "format": "出力形式",
        "mp3_unavailable": "MP3 は使えません（ffmpeg が見つからないか機能不足）",
        "output_dir": "保存フォルダ",
        "browse": "参照...",
        "open": "開く",
        "generate": "生成",
        "cancel": "中止",
        "ready": "準備完了",
        "running": "生成中...",
        "cancelled": "中止しました",
        "done": "生成しました: {name}",
        "failed": "失敗しました（終了コード {code}）",
        "tab_history": "作った曲",
        "tab_log": "ログ",
        "col_time": "時刻",
        "col_genre": "ジャンル",
        "col_seed": "シード",
        "col_bpm": "BPM",
        "col_channels": "ch",
        "col_format": "形式",
        "col_file": "ファイル",
        "play": "再生",
        "show_in_folder": "フォルダで表示",
        "copy_repro": "再現コマンドをコピー",
        "export_as": "別の形式でも書き出す",
        "load_settings": "設定に読み込む",
        "copied": "再現コマンドをコピーしました",
        "no_selection": "曲が選ばれていません",
        "error": "エラー",
        "invalid_seed": "シードは整数で入力してください。",
        "invalid_tempo": "テンポは {lo}〜{hi} の整数で、範囲は「小さい方 〜 大きい方」で入力してください。",
        "no_genre": "ジャンルを選んでください。",
        "exit_args": "指定がジャンルに合いません（テンポ・チャンネル数など）。",
        "exit_generate": "曲の生成・検査で問題が起きました。別のシードを試してください。",
        "exit_output": "ファイルを書き込めませんでした。保存フォルダを確かめてください。",
        "exit_ffmpeg": "MP3 の書き出しに必要な ffmpeg（libopenmpt・libmp3lame 入り）が見つかりません。"
                       "ほかの形式を選ぶか、ffmpeg を入れてください。",
        "exit_unexpected": "想定外のエラーです。「ログ」タブに詳細があります。",
        "start_failed": "CLI を起動できませんでした。",
        "play_failed": "このファイルを開くアプリが見つかりませんでした。\n\n"
                       "MOD/XM/S3M/IT は OpenMPT などのトラッカープレイヤーで再生できます。"
                       "「別の形式でも書き出す」で MP3 や MIDI にすることもできます。",
        "file_missing": "ファイルが見つかりません: {path}",
        "about": "ModWeaver {version}\n{url}\n\nトラッカー音楽を手続き的に自動生成します。",
        "cli_help_title": "CLI の使い方",
    },
    "en": {
        "title": "ModWeaver",
        "menu_file": "File",
        "menu_open_folder": "Open Output Folder",
        "menu_quit": "Quit",
        "menu_view": "View",
        "menu_language": "Language (言語)",
        "menu_help": "Help",
        "menu_cli_help": "CLI Usage...",
        "menu_about": "About ModWeaver",
        "loading": "Loading the genre list...",
        "load_failed": "Could not load the genre list from the CLI.",
        "genres": "Genres",
        "search": "Search:",
        "all_categories": "All",
        "random_genre": "Pick a random genre",
        "random_genre_desc": "Each time, a genre is picked at random from those that can use the settings below "
                             "(tempo, channels).",
        "category": "Category",
        "aliases": "Aliases",
        "tempo_limit": "tempo {lo}-{hi}",
        "channel_choices": "channels {choices}",
        "settings": "Settings",
        "tempo": "Tempo (BPM)",
        "auto_genre": "Let the genre decide",
        "fixed": "Fixed",
        "range": "Range",
        "channels": "Channels",
        "seed": "Seed",
        "seed_random": "Random each time",
        "format": "Format",
        "mp3_unavailable": "MP3 is unavailable (ffmpeg missing or lacking features)",
        "output_dir": "Output folder",
        "browse": "Browse...",
        "open": "Open",
        "generate": "Generate",
        "cancel": "Cancel",
        "ready": "Ready",
        "running": "Generating...",
        "cancelled": "Cancelled",
        "done": "Generated: {name}",
        "failed": "Failed (exit code {code})",
        "tab_history": "Songs",
        "tab_log": "Log",
        "col_time": "Time",
        "col_genre": "Genre",
        "col_seed": "Seed",
        "col_bpm": "BPM",
        "col_channels": "ch",
        "col_format": "Format",
        "col_file": "File",
        "play": "Play",
        "show_in_folder": "Show in Folder",
        "copy_repro": "Copy Command",
        "export_as": "Export As",
        "load_settings": "Load into Settings",
        "copied": "Copied the command to reproduce this song",
        "no_selection": "No song selected",
        "error": "Error",
        "invalid_seed": "The seed must be an integer.",
        "invalid_tempo": "Tempo must be integers from {lo} to {hi}, with the range written low to high.",
        "no_genre": "Choose a genre.",
        "exit_args": "The settings do not suit the genre (tempo, channels, ...).",
        "exit_generate": "Generating or checking the song failed. Try another seed.",
        "exit_output": "Could not write the file. Check the output folder.",
        "exit_ffmpeg": "MP3 output needs ffmpeg built with libopenmpt and libmp3lame, which was not found. "
                       "Choose another format or install ffmpeg.",
        "exit_unexpected": "An unexpected error occurred. See the Log tab for details.",
        "start_failed": "Could not start the CLI.",
        "play_failed": "No application was found to open this file.\n\n"
                       "MOD/XM/S3M/IT files play in tracker players such as OpenMPT. "
                       "You can also use \"Export As\" to make an MP3 or MIDI file.",
        "file_missing": "File not found: {path}",
        "about": "ModWeaver {version}\n{url}\n\nProcedural tracker music generator.",
        "cli_help_title": "CLI Usage",
    },
}

LANGUAGES = (("ja", "日本語"), ("en", "English"))


def default_language() -> str:
    """OS のロケールが日本語なら ja、それ以外は en。"""
    try:
        name = locale.getlocale()[0] or ""
    except ValueError:
        name = ""
    return "ja" if name.lower().startswith(("ja", "japanese")) else "en"
