"""試験用バンクの合成（コードだけで作る。声のデータではない＝D1 に抵触しない。VOCAL_DESIGN.md §9）。

``make_test_bank(folder)`` が UTAU 形式（oto.ini＋wav＋modweaver.json）の 25 音節（あ行・か行・さ行・ま行・な行）を作る。
テスト・``modweaver_voice.py make-test-bank``（取り込み・試聴の動作確認）で使う。品質は「母音が聞き分けられる」程度。
"""
from __future__ import annotations

import json
import math
import random
from pathlib import Path

from .wavio import write_wav16

F0 = 220.0
VOWELS = {   # ((中心 Hz, 帯域 Hz), ...)
    "a": ((800, 80), (1200, 90), (2600, 120), (3300, 150)),
    "i": ((300, 60), (2300, 90), (3000, 120), (3400, 150)),
    "u": ((350, 60), (1300, 90), (2400, 120), (3300, 150)),
    "e": ((500, 70), (1900, 90), (2600, 120), (3300, 150)),
    "o": ((500, 70), (900, 80), (2500, 120), (3300, 150)),
}
GAINS = {"i": (1.0, 1.4, 0.8, 0.5)}
DEFAULT_GAINS = (1.0, 0.8, 0.5, 0.35)
KANA = {
    "": "あいうえお", "k": "かきくけこ", "s": "さしすせそ", "m": "まみむめも", "n": "なにぬねの",
}
CONSONANT_MS = {"": 0, "k": 25, "s": 70, "m": 55, "n": 45}
LEAD_MS, VOWEL_MS, TAIL_MS = 30, 420, 25


def _resonate(x: list[float], fc: float, bw: float, rate: int) -> list[float]:
    r = math.exp(-math.pi * bw / rate)
    c1, c2 = 2 * r * math.cos(2 * math.pi * fc / rate), -r * r
    g = 1 - c1 - c2
    y1 = y2 = 0.0
    out = []
    for v in x:
        y = g * v + c1 * y1 + c2 * y2
        out.append(y)
        y2, y1 = y1, y
    return out


def _vowel(v: str, n: int, rate: int, rng: random.Random) -> list[float]:
    src, ph, prev = [], 0.0, 0.0
    for i in range(n):
        t = i / rate
        ph += F0 * (1 + 0.01 * math.sin(2 * math.pi * 5.5 * t)) / rate
        ph -= math.floor(ph)
        p = 0.5 * (1 - math.cos(math.pi * ph / 0.6)) if ph < 0.6 else math.cos(math.pi * (ph - 0.6) / 0.8)
        src.append((p - prev) * 12)
        prev = p
    mix = [0.0] * n
    for (fc, bw), g in zip(VOWELS[v], GAINS.get(v, DEFAULT_GAINS)):
        for i, y in enumerate(_resonate(src, fc, bw, rate)):
            mix[i] += y * g
    return [m + rng.uniform(-0.01, 0.01) for m in mix]


def _consonant(c: str, n: int, rate: int, rng: random.Random) -> list[float]:
    noise = [rng.uniform(-1, 1) for _ in range(n)]
    if c == "k":
        out = _resonate(noise, 1800, 600, rate)
    elif c == "s":
        out = [b - a for a, b in zip([0.0] + noise, noise)]          # 高域寄りの雑音
    else:                                                            # m・n: 低域の鼻音の唸り
        out = _resonate([math.sin(2 * math.pi * F0 * i / rate) + 0.3 * x for i, x in enumerate(noise)],
                        300 if c == "m" else 400, 100, rate)
    return [v * math.sin(math.pi * (i + 0.5) / n) ** 0.5 for i, v in enumerate(out)]


def make_syllable(c: str, v: str, rate: int, seed: int = 0) -> tuple[list[float], int]:
    """(波形, 子音の長さ ms)。波形は 先頭の無音 → 子音 → 母音 → 末尾の無音。"""
    rng = random.Random(seed)
    ms = rate / 1000.0
    cn = round(CONSONANT_MS[c] * ms)
    vo = _vowel(v, round(VOWEL_MS * ms), rate, rng)
    peak = max(abs(a) for a in vo) or 1.0
    vo = [a / peak * 0.7 for a in vo]
    attack = round(12 * ms)
    for i in range(min(attack, len(vo))):
        vo[i] *= (i + 1) / attack
    rel = round(40 * ms)
    for i in range(rel):
        vo[-1 - i] *= (i + 1) / rel
    cs = [a * 0.45 for a in _consonant(c, cn, rate, rng)] if cn else []
    return [0.0] * round(LEAD_MS * ms) + cs + vo + [0.0] * round(TAIL_MS * ms), CONSONANT_MS[c]


def make_test_bank(folder: Path, rate: int = 22050, encoding: str = "utf-8") -> list[str]:
    """``folder`` に試験用バンクを書く。戻り値: 別名のリスト。oto.ini の文字コードは ``encoding``（cp932 も試せる）。"""
    folder.mkdir(parents=True, exist_ok=True)
    lines, aliases = [], []
    for c, row in KANA.items():
        for v, kana in zip("aiueo", row):
            wave_, cms = make_syllable(c, v, rate, seed=len(aliases))
            name = f"{c}{v}.wav"
            write_wav16(folder / name, rate, wave_)
            pre = cms if cms else 10
            lines.append(f"{name}={kana},{LEAD_MS},{pre + 40},-{TAIL_MS},{pre},{min(pre, 20)}")
            aliases.append(kana)
    (folder / "oto.ini").write_bytes(("\n".join(lines) + "\n").encode(encoding))
    (folder / "modweaver.json").write_text(json.dumps({
        "id": folder.name if folder.name.replace("-", "").replace("_", "").isalnum() else "testbank",
        "lang": "ja", "alias_style": "auto",
        "credit": "Synthetic test bank generated by ModWeaver (no third-party material)",
        "credit_required": True, "terms_url": "", "terms_checked": True,
        "notes": "generated by modweaver_voice.py make-test-bank", "alias_map": {},
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return aliases
